package uk.co.renbinden.libdnd.item;

import uk.co.renbinden.libdnd.registry.Registry;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Predicate;
import java.util.stream.Collectors;

import static uk.co.renbinden.libdnd.item.adventuringgear.phb.PhbAdventuringGearType.*;
import static uk.co.renbinden.libdnd.item.armor.phb.PhbArmorType.*;
import static uk.co.renbinden.libdnd.item.food.phb.PhbFoodType.*;
import static uk.co.renbinden.libdnd.item.tool.phb.PhbToolType.*;
import static uk.co.renbinden.libdnd.item.tradegood.phb.PhbTradeGoodType.*;
import static uk.co.renbinden.libdnd.item.trinket.phb.PhbTrinketType.*;
import static uk.co.renbinden.libdnd.item.weapon.phb.PhbWeaponType.*;

public final class ItemRegistry implements Registry<ItemType> {

    private final Map<String, ItemType> itemTypes;

    public ItemRegistry(Map<String, ItemType> itemTypes) {
        this.itemTypes = itemTypes;
    }

    public static final class Builder {
        private final List<ItemType> itemTypes;

        public Builder() {
            this.itemTypes = new ArrayList<>();
        }

        public Builder addPhbItems() {
            itemTypes.addAll(List.of(
                    // Adventuring gear
                    ABACUS,
                    ACID_VIAL,
                    ALCHEMISTS_FIRE_FLASK,
                    ARROW,
                    BLOWGUN_NEEDLE,
                    CROSSBOW_BOLT,
                    SLING_BULLET,
                    ANTITOXIN,
                    CRYSTAL,
                    ORB,
                    ROD,
                    STAFF,
                    WAND,
                    BACKPACK,
                    BALL_BEARINGS,
                    BARREL,
                    BASKET,
                    BEDROLL,
                    BELL,
                    BLANKET,
                    BLOCK_AND_TACKLE,
                    BOOK,
                    GLASS_BOTTLE,
                    BUCKET,
                    CALTROPS,
                    CANDLE,
                    CROSSBOW_BOLT_CASE,
                    MAP_OR_SCROLL_CASE,
                    CHAIN,
                    CHALK,
                    CHEST,
                    CLIMBERS_KIT,
                    COMMON_CLOTHES,
                    COSTUME_CLOTHES,
                    FINE_CLOTHES,
                    TRAVELERS_CLOTHES,
                    COMPONENT_POUCH,
                    CROWBAR,
                    SPRIG_OF_MISTLETOE,
                    TOTEM,
                    WOODEN_STAFF,
                    YEW_WAND,
                    FISHING_TACKLE,
                    FLASK_OR_TANKARD,
                    GRAPPLING_HOOK,
                    HAMMER,
                    SLEDGE_HAMMER,
                    HEALERS_KIT,
                    AMULET,
                    EMBLEM,
                    RELIQUARY,
                    HOLY_WATER,
                    HOURGLASS,
                    HUNTING_TRAP,
                    INK,
                    INK_PEN,
                    JUG_OR_PITCHER,
                    LADDER,
                    LAMP,
                    BULLSEYE_LANTERN,
                    HOODED_LANTERN,
                    LOCK,
                    MAGNIFYING_GLASS,
                    MANACLES,
                    MESS_KIT,
                    STEEL_MIRROR,
                    OIL,
                    PAPER,
                    PARCHMENT,
                    PERFUME,
                    MINERS_PICK,
                    PITON,
                    BASIC_POISON,
                    POLE,
                    IRON_POT,
                    POTION_OF_HEALING,
                    POUCH,
                    QUIVER,
                    PORTABLE_RAM,
                    RATIONS,
                    ROBES,
                    HEMPEN_ROPE,
                    SILK_ROPE,
                    SACK,
                    MERCHANTS_SCALE,
                    SEALING_WAX,
                    SHOVEL,
                    SIGNAL_WHISTLE,
                    SIGNET_RING,
                    SOAP,
                    SPELLBOOK,
                    IRON_SPIKES,
                    SPYGLASS,
                    TWO_PERSON_TENT,
                    TINDERBOX,
                    TORCH,
                    VIAL,
                    WATERSKIN,
                    WHETSTONE,
                    // Armor
                    PADDED_ARMOR,
                    LEATHER_ARMOR,
                    STUDDED_LEATHER_ARMOR,
                    HIDE_ARMOR,
                    CHAIN_SHIRT_ARMOR,
                    SCALE_MAIL_ARMOR,
                    BREASTPLATE_ARMOR,
                    HALF_PLATE_ARMOR,
                    RING_MAIL_ARMOR,
                    CHAIN_MAIL_ARMOR,
                    SPLINT_ARMOR,
                    PLATE_ARMOR,
                    SHIELD,
                    // Food
                    ALE_GALLON,
                    ALE_MUG,
                    BANQUET,
                    BREAD_LOAF,
                    CHEESE_HUNK,
                    SQUALID_MEAL,
                    POOR_MEAL,
                    MODEST_MEAL,
                    COMFORTABLE_MEAL,
                    WEALTHY_MEAL,
                    ARISTOCRATIC_MEAL,
                    MEAT_CHUNK,
                    COMMON_WINE,
                    FINE_WINE,
                    // Tools
                    ALCHEMISTS_SUPPLIES,
                    BREWERS_SUPPLIES,
                    CALLIGRAPHERS_SUPPLIES,
                    CARPENTERS_TOOLS,
                    CARTOGRAPHERS_TOOLS,
                    COBBLERS_TOOLS,
                    COOKS_UTENSILS,
                    GLASSBLOWERS_TOOLS,
                    JEWELERS_TOOLS,
                    LEATHERWORKERS_TOOLS,
                    MASONS_TOOLS,
                    PAINTERS_SUPPLIES,
                    POTTERS_TOOLS,
                    SMITHS_TOOLS,
                    TINKERS_TOOLS,
                    WEAVERS_TOOLS,
                    WOODCARVERS_TOOLS,
                    DISGUISE_KIT,
                    FORGERY_KIT,
                    DICE_SET,
                    DRAGONCHESS_SET,
                    PLAYING_CARD_SET,
                    THREE_DRAGON_ANTE_SET,
                    HERBALISM_KIT,
                    BAGPIPES,
                    DRUM,
                    DULCIMER,
                    FLUTE,
                    LUTE,
                    LYRE,
                    HORN,
                    PAN_FLUTE,
                    SHAWM,
                    VIOL,
                    NAVIGATORS_TOOLS,
                    POISONERS_TOOLS,
                    THIEVES_TOOLS,
                    CAMEL,
                    DONKEY,
                    MULE,
                    ELEPHANT,
                    DRAFT_HORSE,
                    RIDING_HORSE,
                    MASTIFF,
                    PONY,
                    WARHORSE,
                    PADDED_BARDING,
                    LEATHER_BARDING,
                    STUDDED_LEATHER_BARDING,
                    HIDE_BARDING,
                    CHAIN_SHIRT_BARDING,
                    SCALE_MAIL_BARDING,
                    BREASTPLATE_BARDING,
                    HALF_PLATE_BARDING,
                    RING_MAIL_BARDING,
                    CHAIN_MAIL_BARDING,
                    SPLINT_BARDING,
                    PLATE_BARDING,
                    BIT_AND_BRIDLE,
                    CARRIAGE,
                    CART,
                    CHARIOT,
                    FEED,
                    EXOTIC_SADDLE,
                    MILITARY_SADDLE,
                    PACK_SADDLE,
                    RIDING_SADDLE,
                    SADDLEBAGS,
                    SLED,
                    STABLING,
                    WAGON,
                    GALLEY,
                    KEELBOAT,
                    LONGSHIP,
                    ROWBOAT,
                    SAILING_SHIP,
                    WARSHIP,
                    // Trade good
                    WHEAT,
                    FLOUR,
                    CHICKEN,
                    SALT,
                    IRON,
                    CANVAS,
                    COPPER,
                    COTTON_CLOTH,
                    GINGER,
                    GOAT,
                    CINNAMON,
                    PEPPER,
                    SHEEP,
                    CLOVES,
                    PIG,
                    SILVER,
                    LINEN,
                    SILK,
                    COW,
                    SAFFRON,
                    OX,
                    GOLD,
                    PLATINUM,
                    // Weapons
                    CLUB,
                    DAGGER,
                    GREATCLUB,
                    HANDAXE,
                    JAVELIN,
                    LIGHT_HAMMER,
                    MACE,
                    QUARTERSTAFF,
                    SICKLE,
                    SPEAR,
                    LIGHT_CROSSBOW,
                    DART,
                    SHORTBOW,
                    SLING,
                    BATTLEAXE,
                    FLAIL,
                    GLAIVE,
                    GREATAXE,
                    GREATSWORD,
                    HALBERD,
                    LANCE,
                    LONGSWORD,
                    MAUL,
                    MORNINGSTAR,
                    PIKE,
                    RAPIER,
                    SCIMITAR,
                    SHORTSWORD,
                    TRIDENT,
                    WAR_PICK,
                    WARHAMMER,
                    WHIP,
                    BLOWGUN,
                    HAND_CROSSBOW,
                    HEAVY_CROSSBOW,
                    LONGBOW,
                    NET,
                    // Trinkets
                    MUMMIFIED_GOBLIN_HAND,
                    PIECE_OF_CRYSTAL,
                    FOREIGN_GOLD_COIN,
                    STRANGE_DIARY,
                    BRASS_RING,
                    GLASS_CHESS_PIECE,
                    KNUCKLEBONE_DICE,
                    SMALL_IDOL,
                    ROPE_NECKLACE,
                    LAND_DEED,
                    UNKNOWN_BLOCK,
                    CLOTH_DOLL,
                    UNKNOWN_TOOTH,
                    ENORMOUS_SCALE,
                    BRIGHT_GREEN_FEATHER,
                    OLD_DIVINATION_CARD,
                    GLASS_ORB,
                    BRIGHT_RED_EGG,
                    BUBBLE_PIPE,
                    WEIRD_FLESH_JAR,
                    TINY_MUSIC_BOX,
                    WOODEN_HALFLING_STATUETTE,
                    BRASS_RUNE_ORB,
                    MULTICOLORED_STONE_DISK,
                    SILVER_RAVEN_ICON,
                    TEETH_BAG,
                    OBSIDIAN_SHARD,
                    DRAGON_TALON_NECKLACE,
                    OLD_SOCKS,
                    BLANK_BOOK,
                    SILVER_STAR_BADGE,
                    RELATIVES_KNIFE,
                    NAIL_CLIPPING_VIAL,
                    SPARK_DEVICE,
                    WHITE_SEQUINED_GLOVE,
                    VEST_WITH_POCKETS,
                    WEIGHTLESS_STONE_BLOCK,
                    GOBLIN_SKETCH,
                    EMPTY_PERFUME_VIAL,
                    COAL_GEMSTONE,
                    BANNER_CLOTH,
                    LOST_LEGIONNAIRE_INSIGNIA,
                    TINY_SILVER_BELL,
                    MECHANICAL_CANARY,
                    TINY_CHEST,
                    DEAD_SPRITE,
                    METAL_CAN,
                    CLOCKWORK_GOLDFISH,
                    SILVER_SPOON,
                    WOODEN_WHISTLE,
                    DEAD_SCARAB_BEETLE,
                    TWO_TOY_SOLDIERS,
                    SMALL_BOX_OF_BUTTONS,
                    UNLIGHTABLE_CANDLE,
                    TINY_CAGE,
                    OLD_KEY,
                    INDECIPHERABLE_TREASURE_MAP,
                    BROKEN_SWORD_HILT,
                    RABBITS_FOOT,
                    GLASS_EYE,
                    HIDEOUS_CAMEO,
                    SILVER_SKULL,
                    ALABASTER_MASK,
                    STICKY_BLACK_INCENSE,
                    NIGHTCAP_OF_PLEASANT_DREAMS,
                    BONE_CALTROP,
                    GOLD_MONOCLE_FRAME,
                    COLORFUL_CUBE,
                    CRYSTAL_KNOB,
                    PINK_DUST,
                    BEAUTIFUL_SONG_FRAGMENT,
                    SILVER_TEARDROP_EARRING,
                    DISTURBING_EGGSHELL,
                    SLEEPING_CAT_FAN,
                    BONE_PIPES,
                    FOUR_LEAF_CLOVER_BOOK,
                    CONTRAPTION_DRAWING,
                    ORNATE_SCABBARD,
                    MURDER_PARTY_INVITATION,
                    BRONZE_PENTACLE,
                    PURPLE_HANDKERCHIEF,
                    HALF_FLOORPLAN,
                    STYLISH_CLOTH_CAP,
                    BANK_DEPOSIT_RECEIPT,
                    TORN_DIARY,
                    EMPTY_SILVER_SNUFFBOX,
                    IRON_HOLY_SYMBOL,
                    LEGENDARY_HERO_BOOK,
                    DRAGON_BLOOD_VIAL,
                    ANCIENT_ELVEN_ARROW,
                    UNBENDABLE_NEEDLE,
                    ORNATE_DWARVEN_BROOCH,
                    EMPTY_WINE_BOTTLE,
                    MOSAIC_TILE,
                    PETRIFIED_MOUSE,
                    PIRATE_FLAG,
                    MECHANICAL_CRAB,
                    GRIFFON_GREASE,
                    WORM_IN_A_BOX,
                    HEROS_ASHES
            ));
            return this;
        }

        public Builder addItem(ItemType item) {
            itemTypes.add(item);
            return this;
        }

        public ItemRegistry build() {
            return new ItemRegistry(itemTypes.stream().collect(Collectors.toMap(ItemType::getIdentifier, itemType -> itemType)));
        }
    }

    public ItemType getByIdentifier(String identifier) {
        return itemTypes.get(identifier.toLowerCase());
    }

    public List<ItemType> getAllMatching(Predicate<ItemType> predicate) {
        return itemTypes.values().stream().filter(predicate).toList();
    }

    public <T extends ItemType> List<T> getAllOfType(Class<T> type) {
        return itemTypes.values().stream().filter(itemType -> type.isAssignableFrom(itemType.getClass()))
                .map(type::cast)
                .toList();
    }

}
